Add eslint-plugin-maintainable config
dustinspecker/awesome-eslint pull request #217
Opened 2024-02-10 12:54 UTC by asmyshlyaev177

Just want to share my config, hope it will be useful.

2024-02-10 15:13 UTC, brettz9 commented
Although yours is technically a plugin, I think it should be included under configs since it doesn't actually add any of its own rules (that's normally what configs are used for).

2024-02-10 16:08 UTC, asmyshlyaev177 commented
> Although yours is technically a plugin, I think it should be included under configs since it doesn't actually add any of its own rules (that's normally what configs are used for).

Yeap, other packages do that because can include configs in a plugin, easier than create 2 packages. `Jest` and `Cypress` also come only like plugins and includes configs.

2024-02-10 16:14 UTC, brettz9 commented
I mean your plugin *only* contains configs, so I think it should be listed as we list other configs--not grouped together with other plugins. The Cypress plugin contains its own unique rules, so it makes sense to be grouped differently.

In general, I think configs are of less interest here than plugins because they don't contain any new behaviors. There are effectively an infinite set of possible configs (which any user can express), whereas plugins with unique rules are more finite, so they deserve more prominent and fine-tuned categorization.

2024-02-10 16:36 UTC, asmyshlyaev177 commented
Moved it to configs.

2024-02-11 21:45 UTC, davidjbradshaw commented
Why is it a plugin and not a config?

2024-02-12 08:51 UTC, asmyshlyaev177 commented
> Why is it a plugin and not a config?

Because it is convenient, that can include prettier and couple others handy plugins.

2024-02-12 14:27 UTC, davidjbradshaw commented
@asmyshlyaev177 that is all possible to do with a config.

2024-02-12 14:35 UTC, brettz9 commented
A plugin does have the benefit of allowing one to add one's own rules at a later date if one so chooses.

2024-02-12 14:37 UTC, asmyshlyaev177 commented
> @asmyshlyaev177 that is all possible to do with a config.

Can't, can include config in a plugin but can't put plugin's functionality with config.

2024-02-22 13:08 UTC, asmyshlyaev177 commented
> @asmyshlyaev177 that is all possible to do with a config.

Official docs, point how to include plugin in config, cause I can't find it.
https://eslint.org/docs/latest/extend/shareable-configs
https://eslint.org/docs/latest/extend/plugins

2024-07-11 06:31 UTC, brettz9 requested changes
Seems fine to me if applying the given changes

2024-07-11 06:34 UTC, asmyshlyaev177 commented on readme.md
> +- [eslint-plugin-maintainable](https://github.com/asmyshlyaev177/eslint-plugin-maintainable) - Plugin focused on code quality and simplicity, includes Prettier.
Maybe better to close it for now, there are breaking changes with eslint 9, wait till it settle.

2024-07-11 06:34 UTC, closed without merging